name: Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:
jobs:
  check-changelogs:
    name: Check changelogs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install dependencies
      run: sudo apt install -y fd-find

    - uses: actions/checkout@v4

    - name: git fetch
      run: git fetch origin master:master

    - name: Check changelogs
      run: ./scripts/check-changelogs.sh

