name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.7", "9.0.2", "9.2.5", "9.4.4", "9.6.1"]
    env:
      CONFIG: "--enable-tests"
    steps:
      - uses: actions/checkout@v2
      - name: "Setup haskell"
        uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.8.1.0
      - run: cabal update
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build $CONFIG
      - run: cabal test $CONFIG
      - run: cabal haddock $CONFIG
      - run: cabal sdist

  check-changelogs:
    name: Check changelogs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install dependencies
      run: sudo apt install -y fd-find

    - uses: actions/checkout@v3

    - name: git fetch
      run: git fetch origin master:master

    - name: Check changelogs
      run: ./scripts/check-changelogs.sh
